ENGR00280171 CTS testEnterProximity_noexpire cause android reboot
The case will request network location provider, which only available
with gms packages. Without gms package, it will tricker below exception
on system server, which will reboot android framework:
threadid=12: thread exiting with uncaught exception (group=0x418ec700)
*** FATAL EXCEPTION IN SYSTEM PROCESS: android.server.ServerThread
java.lang.IllegalArgumentException: provider doesn't exisit: null
at com.android.server.LocationManagerService.requestLocationUpdatesLocked
(LocationManagerService.java:1323)
at com.android.server.LocationManagerService.requestLocationUpdatesLocked
(LocationManagerService.java:1302)

Signed-off-by: guoyin.chen <guoyin.chen@freescale.com>